Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-05, with the labels that each got.

#511 Remove MorLockTestApp from Q35 and SBSA
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: type:enhancement, language:python, impact:non-functional

#528 Output Results of Failure Exempt Tests on Q35 and SBSA
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python

#516 Generate the Paging Audit When Running DxePagingAuditTestApp on Q35 and SBSA
  .azurepipelines/Platform-Build-Job.yml
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
  QemuPkg/Plugins/VirtualDriveManager/VirtualDriveManager.py
Labels: type:enhancement, language:python

#539 Release.yaml: Update Mu DevOps 2.3.0 to 2.5.2
  .azurepipelines/Release.yml
Labels: impact:non-functional, semver:patch

#545 Add POPCNT option to Q35 CPU
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, impact:non-functional

#553 Allow TEST_REGEX without RUN_TESTS=TRUE
  QemuPkg/Plugins/VirtualDriveManager/VirtualDriveManager.py
Labels: language:python, impact:non-functional, complexity:easy

#489 Build and Run support for a Dfci Enabled Device Under Test
  DfciDutFiles/BuildDfci.py
  DfciDutFiles/RunDfci.py
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: type:documentation, language:python

#571 Fix Links and Remove Unnecessary Sections in Readme Files
  Platforms/Docs/Q35/Features/feature_colorbar.md
  Platforms/Docs/Q35/Features/feature_config.md
  Platforms/Docs/Q35/QemuQ35_ReadMe.md
  Platforms/Docs/Q35/debugging.md
  Platforms/Docs/SBSA/QemuSbsa_ReadMe.md
  Readme.rst
Labels: type:documentation, impact:non-functional
