Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-04, with the labels that each got.

#464 Add back missing run variable from pipeline change
  .azurepipelines/Platform-Build-Job.yml
  .azurepipelines/Platform-Build-VS.yml
Labels: impact:non-functional

#468 Fix "Temp" references in repo
  Platforms/QemuQ35Pkg/Docs/QemuQ35_ReadMe.md
  Platforms/QemuQ35Pkg/Library/MsPlatformDevicesLibQemuQ35/MsPlatformDevicesLib.c
  Platforms/QemuQ35Pkg/Library/PlatformDebugLibIoPort/ReadMe.md
  Platforms/QemuQ35Pkg/QemuQ35Pkg.ci.yaml
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dec
  Platforms/QemuQ35Pkg/QemuVideoDxe/ReadMe.md
Labels: impact:non-functional

#241 Add a build flag to build/run Q35 without SMM
  .azurepipelines/Platform-Build-Job.yml
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuQ35Pkg/PlatformPei/Platform.c
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dec
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
Labels: language:python

#497 Update Build-UefiExt.yaml to publish on manual action.
  .github/workflows/Build-UefiExt.yaml
Labels: impact:non-functional

#496 Enable features used by the Windows hypervisor
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python

#512 Fix DeviceIdTest on Q35 and SBSA
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: language:python

#515 Publish "No SMM" Q35 binaries on release
  .azurepipelines/templates/Job-Publish.yml
  Platforms/QemuQ35Pkg/NugetPublishing/ReleaseNoSmmConfig.yaml
Labels: impact:non-functional, semver:minor

#473 Add FrontPageButtons to QemuQ35Pkg
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
  QemuPkg/FrontPageButtons/FrontPageButtons.c
  QemuPkg/FrontPageButtons/FrontPageButtons.inf
  QemuPkg/QemuPkg.ci.yaml
  QemuPkg/QemuPkg.dsc
Labels: type:enhancement

#475 Transition virtual drive functionality to a Helper Plugin
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
  QemuPkg/Plugins/VirtualDriveManager/VirtualDriveManager.py
  QemuPkg/Plugins/VirtualDriveManager/VirtualDriveManager_plug_in.yaml
Labels: language:python, impact:non-functional

#506 Enable Advanced Logger in DXE on Q35
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: type:enhancement
