Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-01, with the labels that each got.

#198 Add Memory Protection Build Flag to Q35
  Platforms/QemuQ35Pkg/Docs/Features/feature_memoryprotection_Q35.md
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuQ35Pkg/PlatformPei/Platform.c
  Platforms/QemuQ35Pkg/PlatformPei/PlatformPei.inf
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dec
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: type:documentation, language:python

#239 Add build flag to switch default UI
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: impact:non-functional

#247 QemuRunner.py: Allow OS image paths with spaces
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, impact:non-functional

#243 Added color bars supported by Q35 documentation
  Platforms/QemuQ35Pkg/Docs/Features/Images/Colorbars.jpg
  Platforms/QemuQ35Pkg/Docs/Features/feature_colorbar.md
  Platforms/QemuQ35Pkg/Docs/QemuQ35_ReadMe.md
Labels: type:documentation, impact:non-functional
