Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-09, with the labels that each got.

#691 QemuQ35Pkg/SmmAccess: Add missing include guard
  Platforms/QemuQ35Pkg/SmmAccess/SmramInternal.h
Labels: type:bug, impact:non-functional

#695 Remove Unused Environment Variables
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python, impact:non-functional

#705 QemuQ35Pkg/PlatformBuild.py: Make workspace root stable
  Platforms/QemuQ35Pkg/PlatformBuild.py
Labels: type:bug, language:python, impact:non-functional

#702 Clean-up Q35 and Sbsa PlatformBuild.py
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python, impact:non-functional

#710 Fixing selfhosted agent on AARCH64 systems
  .azurepipelines/MuDevOpsWrapper.yml
  .azurepipelines/Platform-Build-GCC5.yml
  .azurepipelines/Platform-Build-VS.yml
Labels: impact:non-functional
