Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-02, with the labels that each got.

#287 .azurepipelines: Update for mu_devops 2.0.0 changes
  Platforms/QemuQ35Pkg/.azurepipelines/Ubuntu-GCC5.yml
  Platforms/QemuQ35Pkg/.azurepipelines/Windows-VS.yml
  Platforms/QemuSbsaPkg/.azurepipelines/Ubuntu-GCC5.yml
Labels: impact:non-functional

#279 Fix shared and non-shared crypto in DSC
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: impact:non-functional, impact:testing

#288 Bump Fedora-35 test container image to `5b8a008`
  Platforms/QemuQ35Pkg/.azurepipelines/Ubuntu-GCC5.yml
  Platforms/QemuSbsaPkg/.azurepipelines/Ubuntu-GCC5.yml
Labels: impact:non-functional

#325 Job-Publish.yml: Remove temp NuGet publish workaround
  .azurepipelines/NugetPublish.py
  .azurepipelines/templates/Job-Publish.yml
  pip-requirements.txt
Labels: impact:non-functional

#340 QemuQ35Pkg.dsc: Add stack cookie support libs
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: type:bug, impact:non-functional

#352 Readme.rst: Refresh the readme
  Readme.rst
  RepoDetails.md
Labels: type:documentation, impact:non-functional

#353 .gitmodules: Add default tracking branch for MU_FEATURE_DFCI
  .gitmodules
Labels: impact:non-functional

#389 QemuQ35Pkg.dsc: Remove Redundant Library Class
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: platform:Q35, impact:non-functional
