Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-08, with the labels that each got.

#658 .azurepipelines: Centralize and update Windows QEMU version (2023.7.25)
  .azurepipelines/Platform-Build-VS.yml
  .azurepipelines/Release.yml
  .azurepipelines/WindowsQemuVersion.json
Labels: type:dependencies, impact:non-functional

#661 QemuRunner: Use NVMe for OS boot
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, impact:non-functional, semver:patch

#671 QemuSbsaPkg.dsc: Don't use BaseMemoryLibOptDxe for MM_STANDALONE
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: type:bug

#674 Platforms/Docs: Refresh features in QEMU Q35 readme
  Platforms/Docs/Common/Features/feature_memoryprotection.md
  Platforms/Docs/Q35/QemuQ35_ReadMe.md
Labels: type:documentation, impact:non-functional

#682 Resolve mws deprecations
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python, impact:non-functional

#669 Allow passing any CPU model while invoking QEMU.
  Platforms/QemuQ35Pkg/CpuInfoDxe/CpuInfoDxe.c
  Platforms/QemuQ35Pkg/CpuInfoDxe/CpuInfoDxe.inf
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
Labels: language:python, type:feature-request

#686 QemuRunner: Prevent virtual drive unknown image format warning
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: type:bug, language:python, impact:non-functional

#687 Remove physical presence from Q35 and SBSA
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: impact:security
