Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-07, with the labels that each got.

#624 Update Test Exemptions
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python

#625 Use correct Openssl inf for SBSA
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: impact:security

#634 Release.yml: Acquire OpenSSL via apt-get
  .azurepipelines/Release.yml
Labels: type:bug, impact:non-functional

#635 QemuRunner: Add support for QCOW2 images
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python

#633 Fix support for TPM on Q35
  Platforms/Docs/Q35/Features/feature_tpm.md
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
  QemuPkg/Library/QemuPreUefiEventLogLibNull/QemuPreUefiEventLogLibNull.c
  QemuPkg/Library/QemuPreUefiEventLogLibNull/QemuPreUefiEventLogLibNull.inf
  QemuPkg/QemuPkg.dsc
Labels: language:python, platform:Q35

#645 Use "usb-tablet" instead of "usb-mouse" as the pointer device
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: type:enhancement, language:python, impact:non-functional

#646 Add BIOS version and release date to SMBIOS
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: type:enhancement, language:python, impact:non-functional
