Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-06, with the labels that each got.

#585 Release.yaml: Update to work with self-hosted agent change
  .azurepipelines/Release.yml
Labels: semver:patch

#589 Set the Type3 SN different from the Type1 SN
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, impact:breaking-change, impact:testing

#605 Adding ARM build on self-hosted images
  .azurepipelines/Platform-Build-GCC5.yml
Labels: platform:SBSA

#567 Update Project CI & Devcontainer to use the Project MU containers
  .azurepipelines/Platform-Build-GCC5.yml
  .azurepipelines/Platform-Build-Job.yml
  .azurepipelines/Release.yml
  .devcontainer/devcontainer.json
Labels: impact:non-functional

#611 Removed extra indirection of policy creation from a separate model
  Platforms/QemuQ35Pkg/ConfigKnobs/ConfigKnobs.inf
  Platforms/QemuQ35Pkg/PolicyDataGfx/PolicyDataGfx.c
  Platforms/QemuQ35Pkg/PolicyDataGfx/PolicyDataGfx.inf
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
  Platforms/QemuSbsaPkg/ConfigKnobs/ConfigKnobs.inf
  Platforms/QemuSbsaPkg/PolicyDataGfx/PolicyDataGfx.c
  Platforms/QemuSbsaPkg/PolicyDataGfx/PolicyDataGfx.inf
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
  Platforms/QemuSbsaPkg/QemuSbsaPkg.fdf
Labels: type:bug
