Repository microsoft/mu_tiano_platforms, pull requests merged in 2023-10, with the labels that each got.

#718 Fixing multiple build instances usage on Linux environment
  QemuPkg/Plugins/VirtualDriveManager/VirtualDriveManager.py
Labels: language:python, impact:non-functional

#742 Docs/Common/Featues: Add Front Page Instructions
  Platforms/Docs/Common/Features/feature_frontpage.md
Labels: type:documentation, impact:non-functional

#745 Add rust-ci scope to Qemu35Pkg and QemuSbsaPkg
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python, impact:non-functional, semver:patch
