Repository microsoft/mu_tiano_platforms, pull requests merged in 2024-02, with the labels that each got.

#840 QemuQ35Pkg: Define SMM_CRYPTO_ARCH
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
Labels: impact:non-functional

#838 Add section to debugging readme for using GDB
  Platforms/Docs/Common/debugging.md
  Platforms/Docs/SBSA/debugging.md
Labels: type:documentation, impact:non-functional

#857 Install the Hash 2 Service Binding Protocol
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: semver:patch

#851 Use qemu external dependency
  .azurepipelines/Platform-Build-VS.yml
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
  QemuPkg/Binaries/qemu-linux_ext_dep.yaml
  QemuPkg/Binaries/qemu-windows_ext_dep.yaml
Labels: language:python, impact:non-functional
