Repository microsoft/mu_tiano_platforms, pull requests merged in 2024-05, with the labels that each got.

#939 Use MdeModulePkg BaseRngLibTimerLib instance
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: impact:non-functional, semver:patch

#940 Add NETWORK_ENABLE option
  Platforms/Docs/Common/building.md
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, platform:Q35, impact:non-functional, semver:patch

#957 Add Additional SSE Instructions to Q35
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: type:bug, language:python, impact:non-functional
