Repository microsoft/mu_tiano_platforms, pull requests merged in 2024-03, with the labels that each got.

#873 Add SSE4.2 to q35 QEMU runner CPU features
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python

#874 Add E1000 rom to QEMU ext dep
  .github/workflows/publish-qemu-bin.yml
Labels: impact:non-functional

#881 Use latest qemu extdep
  QemuPkg/Binaries/qemu-linux_ext_dep.yaml
  QemuPkg/Binaries/qemu-windows_ext_dep.yaml
Labels: impact:non-functional

#882 Add SSE4.1 Instructions to Q35
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
Labels: language:python, impact:non-functional

#876 Create Memory Allocation HOB Entry for QEMU FDT Blob
  Platforms/QemuSbsaPkg/Library/SbsaQemuLib/SbsaQemuLib.inf
  Platforms/QemuSbsaPkg/Library/SbsaQemuLib/SbsaQemuMem.c
Labels: platform:SBSA
