Repository microsoft/mu_tiano_platforms, pull requests merged in 2024-04, with the labels that each got.

#894 Remove UEFI Ext as it has moved to mu_feature_debugger
  .github/workflows/Build-UefiExt.yaml
  UefiDbgExt/dbgexts.cpp
  UefiDbgExt/dbgexts.h
  UefiDbgExt/memory.cpp
  UefiDbgExt/modules.cpp
  UefiDbgExt/readme.md
  UefiDbgExt/tables.cpp
  UefiDbgExt/uefiext.cpp
  UefiDbgExt/uefiext.def
  UefiDbgExt/uefiext.h
  UefiDbgExt/uefiext.rc
  UefiDbgExt/uefiext.sln
  UefiDbgExt/uefiext.vcxproj
Labels: impact:non-functional

#900 Fix console after returning from QEMU
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
  pip-requirements.txt
Labels: language:python

#902 Add HTTP and acpiview commands to UEFI shell
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: impact:non-functional

#905 Move Standalone MM and some PEIM modules to use dynamic stack cookie library
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: platform:Q35, platform:SBSA, impact:security

#915 qemu_extdep: Remove the linux extdep
  QemuPkg/Binaries/qemu-linux_ext_dep.yaml
Labels: impact:non-functional

#919 Refresh Paging Audit Test App CI Exemption
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python

#901 Upgrade default QEMU to v9.0.0
  .github/publish-qemu-config.yml
Labels: impact:non-functional

#929 Added exception handling when `GetConsoleMode` API fails
  Platforms/QemuQ35Pkg/Plugins/QemuRunner/QemuRunner.py
  Platforms/QemuSbsaPkg/Plugins/QemuRunner/QemuRunner.py
Labels: type:bug, language:python, impact:non-functional
