Repository microsoft/mu_tiano_platforms, pull requests merged in 2025-01, with the labels that each got.

#1091 [FF-A] Service/Secure Partition Documentation
  Platforms/QemuSbsaPkg/MsSecurePartition/PartitionGuide.md
  Platforms/QemuSbsaPkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/fdts/qemu_sbsa_mssp_config.dts
Labels: type:documentation, language:python, impact:non-functional

#1100 Use hidparser crate from crates.io
  Cargo.lock
  Cargo.toml
Labels: impact:non-functional

#1101 [FFA][TPM] Fix TPM2_ENABLE flag
  Platforms/QemuSbsaPkg/MsSecurePartition/MsSecurePartition.c
  Platforms/QemuSbsaPkg/MsSecurePartition/MsSecurePartition.inf
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: impact:non-functional

#1102 [FFA] Fixed an issue of symbol unresolved when enabling TPM
  Platforms/QemuSbsaPkg/MsSecurePartition/MsSecurePartition.c
  Platforms/QemuSbsaPkg/QemuSbsaPkg.dsc
Labels: type:bug
