Repository microsoft/mu_tiano_platforms, pull requests merged in 2025-02, with the labels that each got.

#1111 Add Performance Tracing Support
  Platforms/QemuQ35Pkg/QemuQ35Pkg.dsc
  Platforms/QemuQ35Pkg/QemuQ35Pkg.fdf
Labels: type:feature-request

#1117 Cargo: Update dependencies
  Cargo.lock
  Cargo.toml
Labels: impact:non-functional

#1118 [REBASE&FF] Re-enable Rust CI
  .azurepipelines/MuDevOpsWrapper.yml
  .azurepipelines/Platform-Build-GCC5.yml
  .azurepipelines/Platform-Build-VS.yml
  .azurepipelines/Ubuntu-GCC5.yml
  .azurepipelines/Windows-VS.yml
  .pytool/CISettings.py
  Platforms/QemuQ35Pkg/PlatformBuild.py
  Platforms/QemuSbsaPkg/PlatformBuild.py
Labels: language:python, impact:non-functional
